/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List sessions for the authenticated project.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a session and/or dispatch a task.
         *
         *     - Without session_id, without task: creates a new idle session (e.g. for file uploads).
         *     - Without session_id, with task: creates a new session and dispatches the task.
         *     - With session_id, with task: dispatches the task to an existing idle session.
         *     - With session_id, without task: 422 — task is required when targeting an existing session.
         *
         *     If keep_alive is false (default), the session auto-stops when the task finishes.
         *     If keep_alive is true, the session stays idle after the task, ready for follow-ups.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get session details. Use this to poll for task completion and output.
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Soft-delete a session. Stops the sandbox first if still running.
         */
        delete: operations["delete_session_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Session
         * @description Stop a session or the running task.
         *
         *     - strategy=session (default): destroy sandbox entirely, session → stopped.
         *     - strategy=task: stop the running query, session stays alive (→ idle).
         */
        post: operations["stop_session_sessions__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Session Messages
         * @description Return messages for a session with cursor-based pagination (chronological order).
         */
        get: operations["list_session_messages_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browsers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Browser Sessions
         * @description Get paginated list of browser sessions with optional status filtering.
         */
        get: operations["list_browser_sessions_browsers_get"];
        put?: never;
        /**
         * Create Browser Session
         * @description Create a new browser session.
         *
         *     **Pricing:** Browser sessions are charged per hour with tiered pricing:
         *     - Pay As You Go users: $0.06/hour
         *     - Business/Scaleup subscribers: $0.03/hour (50% discount)
         *
         *     The full rate is charged upfront when the session starts.
         *     When you stop the session, any unused time is automatically refunded proportionally.
         *
         *     Billing is rounded up to the minute (minimum 1 minute).
         *     For example, if you stop a session after 30 minutes, you'll be refunded half the charged amount.
         *
         *     **Session Limits:**
         *     - All users: Up to 4 hours per session
         */
        post: operations["create_browser_session_browsers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browsers/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Browser Session
         * @description Get detailed browser session information including status and URLs.
         */
        get: operations["get_browser_session_browsers__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Browser Session
         * @description Stop a browser session.
         *
         *     **Refund:** When you stop a session, unused time is automatically refunded.
         *     If the session ran for less than 1 hour, you'll receive a proportional refund.
         *     Billing is ceil to the nearest minute (minimum 1 minute).
         */
        patch: operations["update_browser_session_browsers__session_id__patch"];
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description Get paginated list of profiles.
         *
         *     Use the `query` parameter to search profiles by name or user_id.
         *     This is useful when you have many profiles and need to find a specific user.
         *
         *     Example: If you set `user_id` to your internal user identifier when creating profiles,
         *     you can later search for that user by passing their identifier as the `query` parameter.
         */
        get: operations["list_profiles_profiles_get"];
        put?: never;
        /**
         * Create Profile
         * @description Profiles allow you to preserve the state of the browser between tasks.
         *
         *     They are most commonly used to allow users to preserve the log-in state in the agent between tasks.
         *     You'd normally create one profile per user and then use it for all their tasks.
         *
         *     You can set a `user_id` when creating a profile to associate it with a user in your system.
         *     This allows you to later search for the profile using the GET /profiles endpoint with a query parameter.
         */
        post: operations["create_profile_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Get profile details.
         */
        get: operations["get_profile_profiles__profile_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Browser Profile
         * @description Permanently delete a browser profile and its configuration.
         */
        delete: operations["delete_browser_profile_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Profile
         * @description Update a browser profile's information.
         */
        patch: operations["update_profile_profiles__profile_id__patch"];
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workspaces
         * @description Get paginated list of workspaces.
         */
        get: operations["list_workspaces_workspaces_get"];
        put?: never;
        /**
         * Create Workspace
         * @description Create a new workspace for persistent shared file storage across sessions.
         */
        post: operations["create_workspace_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace
         * @description Get workspace details.
         */
        get: operations["get_workspace_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Workspace
         * @description Delete a workspace and its S3 data.
         */
        delete: operations["delete_workspace_workspaces__workspace_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Workspace
         * @description Update a workspace's name.
         */
        patch: operations["update_workspace_workspaces__workspace_id__patch"];
        trace?: never;
    };
    "/workspaces/{workspace_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workspace Files
         * @description List files in a workspace's S3 prefix.
         */
        get: operations["list_workspace_files_workspaces__workspace_id__files_get"];
        put?: never;
        post?: never;
        /**
         * Delete Workspace File
         * @description Delete a single file from a workspace.
         */
        delete: operations["delete_workspace_file_workspaces__workspace_id__files_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace Size
         * @description Get current storage usage for a workspace.
         */
        get: operations["get_workspace_size_workspaces__workspace_id__size_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Workspace Files
         * @description Get presigned PUT URLs for uploading files to a workspace.
         */
        post: operations["upload_workspace_files_workspaces__workspace_id__files_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Account Billing
         * @description Get authenticated account information including credit balance and account details.
         */
        get: operations["get_account_billing_billing_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountNotFoundError
         * @description Error response when an account is not found
         */
        AccountNotFoundError: {
            /**
             * Detail
             * @default Account not found
             */
            detail: string;
        };
        /**
         * AccountView
         * @description View model for account information.
         */
        AccountView: {
            /**
             * Name
             * @description The name of the user
             */
            name?: string | null;
            /**
             * Credits Balance USD
             * @description The total credits balance in USD
             */
            totalCreditsBalanceUsd: number;
            /**
             * Monthly Credits Balance USD
             * @description Monthly subscription credits balance in USD
             */
            monthlyCreditsBalanceUsd: number;
            /**
             * Additional Credits Balance USD
             * @description Additional top-up credits balance in USD
             */
            additionalCreditsBalanceUsd: number;
            /**
             * Rate Limit
             * @description The rate limit for the account
             */
            rateLimit: number;
            /**
             * Plan Info
             * @description The plan information
             */
            planInfo: components["schemas"]["PlanInfo"];
            /**
             * Project ID
             * Format: uuid
             * @description The ID of the project
             */
            projectId: string;
        };
        /**
         * BrowserSessionItemView
         * @description View model for representing a browser session in list views.
         */
        BrowserSessionItemView: {
            /**
             * ID
             * Format: uuid
             * @description Unique identifier for the session
             */
            id: string;
            /**
             * Status
             * @description Current status of the session (active/stopped)
             */
            status: components["schemas"]["BrowserSessionStatus"];
            /**
             * Live URL
             * @description URL where the browser can be viewed live in real-time
             */
            liveUrl?: string | null;
            /**
             * CDP URL
             * @description Chrome DevTools Protocol URL for browser automation
             */
            cdpUrl?: string | null;
            /**
             * Timeout At
             * Format: date-time
             * @description Timestamp when the session will timeout
             */
            timeoutAt: string;
            /**
             * Started At
             * Format: date-time
             * @description Timestamp when the session was created and started
             */
            startedAt: string;
            /**
             * Finished At
             * @description Timestamp when the session was stopped (None if still active)
             */
            finishedAt?: string | null;
            /**
             * Proxy Used MB
             * @description Amount of proxy data used in MB
             * @default 0
             */
            proxyUsedMb: string;
            /**
             * Proxy Cost
             * @description Cost of proxy usage in USD
             * @default 0
             */
            proxyCost: string;
            /**
             * Browser Cost
             * @description Cost of browser session hosting in USD
             * @default 0
             */
            browserCost: string;
            /**
             * Agent Session ID
             * @description ID of the agent session that created this browser (None for standalone BaaS sessions)
             */
            agentSessionId?: string | null;
            /**
             * Recording URL
             * @description Presigned URL to download the session recording (available after session ends, if recording was enabled)
             */
            recordingUrl?: string | null;
        };
        /**
         * BrowserSessionListResponse
         * @description Response model for paginated browser session list requests.
         */
        BrowserSessionListResponse: {
            /**
             * Items
             * @description List of browser session views for the current page
             */
            items: components["schemas"]["BrowserSessionItemView"][];
            /**
             * Total Items
             * @description Total number of items in the list
             */
            totalItems: number;
            /**
             * Page Number
             * @description Page number
             */
            pageNumber: number;
            /**
             * Page Size
             * @description Number of items per page
             */
            pageSize: number;
        };
        /**
         * BrowserSessionStatus
         * @description Enumeration of possible browser session states
         *
         *     Attributes:
         *         ACTIVE: Session is currently active and running (browser is running)
         *         STOPPED: Session has been stopped and is no longer active (browser is stopped)
         * @enum {string}
         */
        BrowserSessionStatus: "active" | "stopped";
        /**
         * BrowserSessionUpdateAction
         * @description Available actions that can be performed on a browser session
         *
         *     Attributes:
         *         STOP: Stop the browser session (cannot be undone)
         * @enum {string}
         */
        BrowserSessionUpdateAction: "stop";
        /**
         * BrowserSessionView
         * @description View model for representing a browser session.
         */
        BrowserSessionView: {
            /**
             * ID
             * Format: uuid
             * @description Unique identifier for the session
             */
            id: string;
            /**
             * Status
             * @description Current status of the session (active/stopped)
             */
            status: components["schemas"]["BrowserSessionStatus"];
            /**
             * Live URL
             * @description URL where the browser can be viewed live in real-time
             */
            liveUrl?: string | null;
            /**
             * CDP URL
             * @description Chrome DevTools Protocol URL for browser automation
             */
            cdpUrl?: string | null;
            /**
             * Timeout At
             * Format: date-time
             * @description Timestamp when the session will timeout
             */
            timeoutAt: string;
            /**
             * Started At
             * Format: date-time
             * @description Timestamp when the session was created and started
             */
            startedAt: string;
            /**
             * Finished At
             * @description Timestamp when the session was stopped (None if still active)
             */
            finishedAt?: string | null;
            /**
             * Proxy Used MB
             * @description Amount of proxy data used in MB
             * @default 0
             */
            proxyUsedMb: string;
            /**
             * Proxy Cost
             * @description Cost of proxy usage in USD
             * @default 0
             */
            proxyCost: string;
            /**
             * Browser Cost
             * @description Cost of browser session hosting in USD
             * @default 0
             */
            browserCost: string;
            /**
             * Agent Session ID
             * @description ID of the agent session that created this browser (None for standalone BaaS sessions)
             */
            agentSessionId?: string | null;
            /**
             * Recording URL
             * @description Presigned URL to download the session recording (available after session ends, if recording was enabled)
             */
            recordingUrl?: string | null;
        };
        /**
         * BuAgentSessionStatus
         * @description Session lifecycle status. Progresses through: created → idle → running → idle → ... → stopped / timed_out / error.
         *
         *     - `created`: Sandbox is starting up. The session is not yet ready to accept tasks.
         *     - `idle`: Sandbox is healthy and waiting for a task. You can dispatch a task or upload files.
         *     - `running`: A task is currently being executed by the agent.
         *     - `stopped`: Session was stopped — either explicitly via the stop endpoint, or automatically after task completion (when `keepAlive` is false).
         *     - `timed_out`: Session was cleaned up due to inactivity timeout.
         *     - `error`: Sandbox failed to start or encountered an unrecoverable error.
         * @enum {string}
         */
        BuAgentSessionStatus: "created" | "idle" | "running" | "stopped" | "timed_out" | "error";
        /**
         * BuModel
         * @description The model to use for the agent. Each model has different capabilities and pricing.
         *
         *     - `bu-mini` / `gemini-3-flash`: Gemini 3 Flash — fast and cost-effective. Best for simple, well-defined tasks like form filling or data extraction.
         *     - `bu-max` / `claude-sonnet-4.6`: Claude Sonnet 4.6 — balanced performance. Best for multi-step workflows that require reasoning and decision-making.
         *     - `bu-ultra` / `claude-opus-4.6`: Claude Opus 4.6 — most capable. Best for complex tasks that require advanced reasoning, long-horizon planning, or handling ambiguous instructions.
         * @enum {string}
         */
        BuModel: "bu-mini" | "bu-max" | "bu-ultra" | "gemini-3-flash" | "claude-sonnet-4.6" | "claude-opus-4.6";
        /**
         * CreateBrowserSessionRequest
         * @description Request model for creating a browser session.
         */
        CreateBrowserSessionRequest: {
            /**
             * Profile ID
             * @description The ID of the profile to use for the session
             */
            profileId?: string | null;
            /**
             * Proxy Country Code
             * @description Country code for proxy location. Defaults to US. Set to null to disable proxy.
             * @default us
             */
            proxyCountryCode: components["schemas"]["ProxyCountryCode"] | null;
            /**
             * Timeout
             * @description The timeout for the session in minutes. All users can use up to 240 minutes (4 hours). Pay As You Go users are charged $0.06/hour, subscribers get 50% off.
             * @default 60
             */
            timeout: number;
            /**
             * Browser Screen Width
             * @description Custom screen width in pixels for the browser.
             */
            browserScreenWidth?: number | null;
            /**
             * Browser Screen Height
             * @description Custom screen height in pixels for the browser.
             */
            browserScreenHeight?: number | null;
            /**
             * Allow Resizing
             * @description Whether to allow the browser to be resized during the session (not recommended since it reduces stealthiness).
             * @default false
             */
            allowResizing: boolean;
            /**
             * Custom Proxy
             * @description Custom proxy settings to use for the session. If not provided, our proxies will be used. Custom proxies are available on any active subscription.
             */
            customProxy?: components["schemas"]["CustomProxy"] | null;
            /**
             * Enable Recording
             * @description If True, enables session recording. Defaults to False.
             * @default false
             */
            enableRecording: boolean;
        };
        /**
         * CustomProxy
         * @description Request model for creating a custom proxy.
         */
        CustomProxy: {
            /**
             * Host
             * @description Host of the proxy.
             */
            host: string;
            /**
             * Port
             * @description Port of the proxy.
             */
            port: number;
            /**
             * Username
             * @description Username for proxy authentication.
             */
            username?: string | null;
            /**
             * Password
             * @description Password for proxy authentication.
             */
            password?: string | null;
        };
        /**
         * FileInfo
         * @description A file in a session's workspace.
         */
        FileInfo: {
            /**
             * Path
             * @description File path relative to the session workspace root.
             */
            path: string;
            /**
             * Size
             * @description File size in bytes.
             */
            size: number;
            /**
             * Lastmodified
             * Format: date-time
             * @description When the file was last modified.
             */
            lastModified: string;
            /**
             * Url
             * @description Presigned download URL (60s expiry). Only included when `includeUrls=true`.
             */
            url?: string | null;
        };
        /**
         * FileListResponse
         * @description Paginated file listing with optional presigned download URLs.
         */
        FileListResponse: {
            /** Files */
            files: components["schemas"]["FileInfo"][];
            /**
             * Folders
             * @description Immediate sub-folder names at this prefix level
             */
            folders?: string[];
            /**
             * Nextcursor
             * @description Cursor for the next page. Pass as the `cursor` query parameter to fetch the next page.
             */
            nextCursor?: string | null;
            /**
             * Hasmore
             * @description Whether there are more files beyond this page.
             * @default false
             */
            hasMore: boolean;
        };
        /**
         * FileUploadItem
         * @description A single file to upload.
         */
        FileUploadItem: {
            /**
             * Name
             * @description Filename, e.g. "data.csv"
             */
            name: string;
            /**
             * Contenttype
             * @description MIME type, e.g. "text/csv"
             * @default application/octet-stream
             */
            contentType: string;
            /**
             * Size
             * @description File size in bytes (required for workspace uploads)
             */
            size?: number | null;
        };
        /**
         * FileUploadRequest
         * @description Request body for generating presigned upload URLs.
         */
        FileUploadRequest: {
            /** Files */
            files: components["schemas"]["FileUploadItem"][];
        };
        /**
         * FileUploadResponse
         * @description Presigned upload URLs for the requested files.
         */
        FileUploadResponse: {
            /** Files */
            files: components["schemas"]["FileUploadResponseItem"][];
        };
        /**
         * FileUploadResponseItem
         * @description Presigned upload URL for a single file.
         */
        FileUploadResponseItem: {
            /**
             * Name
             * @description Original filename as requested.
             */
            name: string;
            /**
             * Uploadurl
             * @description Presigned PUT URL. Upload the file by sending a PUT request to this URL with the file content and matching Content-Type header. Expires after 5 minutes.
             */
            uploadUrl: string;
            /**
             * Path
             * @description Path where the file will be stored in the workspace, e.g. "uploads/data.csv".
             */
            path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsufficientCreditsError
         * @description Error response when there are insufficient credits
         */
        InsufficientCreditsError: {
            /**
             * Detail
             * @default Insufficient credits
             */
            detail: string;
        };
        /** MessageListResponse */
        MessageListResponse: {
            /**
             * Messages
             * @description List of messages in chronological order.
             */
            messages: components["schemas"]["MessageResponse"][];
            /**
             * Hasmore
             * @description Whether there are more messages available beyond this page. Use cursor-based pagination with the `after` or `before` query parameters to fetch more.
             */
            hasMore: boolean;
        };
        /**
         * MessageResponse
         * @description A single message from the session's message stream.
         *
         *     Messages represent the agent's actions, observations, and decisions as it executes a task.
         */
        MessageResponse: {
            /**
             * Id
             * Format: uuid
             * @description Unique message identifier.
             */
            id: string;
            /**
             * Sessionid
             * Format: uuid
             * @description ID of the session this message belongs to.
             */
            sessionId: string;
            /**
             * Role
             * @description Message role: "human" for user-submitted tasks, "ai" for agent actions and responses.
             */
            role: string;
            /**
             * Data
             * @description Raw message content. Format depends on the message type — may be plain text, JSON, or structured action data.
             */
            data: string;
            /**
             * Type
             * @description Message category. Common values: `user_message`, `assistant_message`, `browser_action`, `file_operation`, `code_execution`, `integration`, `planning`, `completion`, `browser_action_result`, `browser_action_error`.
             * @default
             */
            type: string;
            /**
             * Summary
             * @description One-liner human-readable description of the message (e.g. "Navigating to google.com", "Clicking element #5"). Useful for building activity feeds.
             * @default
             */
            summary: string;
            /**
             * Screenshoturl
             * @description Browser screenshot captured at the time of this message. Presigned URL, expires after 5 minutes.
             */
            screenshotUrl?: string | null;
            /**
             * Hidden
             * @description Whether this message should be hidden from the user in a chat UI.
             * @default false
             */
            hidden: boolean;
            /**
             * Createdat
             * Format: date-time
             * @description When this message was created.
             */
            createdAt: string;
        };
        /**
         * PlanInfo
         * @description View model for plan information
         */
        PlanInfo: {
            /**
             * Plan Name
             * @description The name of the plan
             */
            planName: string;
            /**
             * Subscription Status
             * @description The status of the subscription
             */
            subscriptionStatus: string | null;
            /**
             * Subscription ID
             * @description The ID of the subscription
             */
            subscriptionId: string | null;
            /**
             * Subscription Current Period End
             * @description The end of the current period
             */
            subscriptionCurrentPeriodEnd: string | null;
            /**
             * Subscription Canceled At
             * @description The date the subscription was canceled
             */
            subscriptionCanceledAt: string | null;
        };
        /**
         * ProfileCreateRequest
         * @description Request model for creating a new profile.
         */
        ProfileCreateRequest: {
            /**
             * Name
             * @description Optional name for the profile
             */
            name?: string | null;
            /**
             * User ID
             * @description Your internal user identifier for this profile. Use this to associate a profile with a user in your system.
             */
            userId?: string | null;
        };
        /**
         * ProfileListResponse
         * @description Response model for paginated profile list requests.
         */
        ProfileListResponse: {
            /**
             * Items
             * @description List of profile views for the current page
             */
            items: components["schemas"]["ProfileView"][];
            /**
             * Total Items
             * @description Total number of items in the list
             */
            totalItems: number;
            /**
             * Page Number
             * @description Page number
             */
            pageNumber: number;
            /**
             * Page Size
             * @description Number of items per page
             */
            pageSize: number;
        };
        /**
         * ProfileNotFoundError
         * @description Error response when a profile is not found
         */
        ProfileNotFoundError: {
            /**
             * Detail
             * @default Profile not found
             */
            detail: string;
        };
        /**
         * ProfileUpdateRequest
         * @description Request model for updating a profile.
         */
        ProfileUpdateRequest: {
            /**
             * Name
             * @description Optional name for the profile
             */
            name?: string | null;
            /**
             * User ID
             * @description Your internal user identifier for this profile. Use this to associate a profile with a user in your system.
             */
            userId?: string | null;
        };
        /**
         * ProfileView
         * @description View model for representing a profile. A profile lets you preserve the login state between sessions.
         *
         *     We recommend that you create a separate profile for each user of your app.
         *     You can assign a user_id to each profile to easily identify which user the profile belongs to.
         */
        ProfileView: {
            /**
             * ID
             * Format: uuid
             * @description Unique identifier for the profile
             */
            id: string;
            /**
             * User ID
             * @description Your internal user identifier for this profile. Use this to associate a profile with a user in your system.
             */
            userId?: string | null;
            /**
             * Name
             * @description Optional name for the profile
             */
            name?: string | null;
            /**
             * Last Used At
             * @description Timestamp when the profile was last used
             */
            lastUsedAt?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Timestamp when the profile was created
             */
            createdAt: string;
            /**
             * Updated At
             * Format: date-time
             * @description Timestamp when the profile was last updated
             */
            updatedAt: string;
            /**
             * Cookie Domains
             * @description List of domain URLs that have cookies stored for this profile
             */
            cookieDomains?: string[] | null;
        };
        /**
         * ProxyCountryCode
         * @enum {string}
         */
        ProxyCountryCode: "ad" | "ae" | "af" | "ag" | "ai" | "al" | "am" | "an" | "ao" | "aq" | "ar" | "as" | "at" | "au" | "aw" | "az" | "ba" | "bb" | "bd" | "be" | "bf" | "bg" | "bh" | "bi" | "bj" | "bl" | "bm" | "bn" | "bo" | "bq" | "br" | "bs" | "bt" | "bv" | "bw" | "by" | "bz" | "ca" | "cc" | "cd" | "cf" | "cg" | "ch" | "ck" | "cl" | "cm" | "co" | "cr" | "cs" | "cu" | "cv" | "cw" | "cx" | "cy" | "cz" | "de" | "dj" | "dk" | "dm" | "do" | "dz" | "ec" | "ee" | "eg" | "eh" | "er" | "es" | "et" | "fi" | "fj" | "fk" | "fm" | "fo" | "fr" | "ga" | "gd" | "ge" | "gf" | "gg" | "gh" | "gi" | "gl" | "gm" | "gn" | "gp" | "gq" | "gr" | "gs" | "gt" | "gu" | "gw" | "gy" | "hk" | "hm" | "hn" | "hr" | "ht" | "hu" | "id" | "ie" | "il" | "im" | "in" | "iq" | "ir" | "is" | "it" | "je" | "jm" | "jo" | "jp" | "ke" | "kg" | "kh" | "ki" | "km" | "kn" | "kp" | "kr" | "kw" | "ky" | "kz" | "la" | "lb" | "lc" | "li" | "lk" | "lr" | "ls" | "lt" | "lu" | "lv" | "ly" | "ma" | "mc" | "md" | "me" | "mf" | "mg" | "mh" | "mk" | "ml" | "mm" | "mn" | "mo" | "mp" | "mq" | "mr" | "ms" | "mt" | "mu" | "mv" | "mw" | "mx" | "my" | "mz" | "na" | "nc" | "ne" | "nf" | "ng" | "ni" | "nl" | "no" | "np" | "nr" | "nu" | "nz" | "om" | "pa" | "pe" | "pf" | "pg" | "ph" | "pk" | "pl" | "pm" | "pn" | "pr" | "ps" | "pt" | "pw" | "py" | "qa" | "re" | "ro" | "rs" | "ru" | "rw" | "sa" | "sb" | "sc" | "sd" | "se" | "sg" | "sh" | "si" | "sj" | "sk" | "sl" | "sm" | "sn" | "so" | "sr" | "ss" | "st" | "sv" | "sx" | "sy" | "sz" | "tc" | "td" | "tf" | "tg" | "th" | "tj" | "tk" | "tl" | "tm" | "tn" | "to" | "tr" | "tt" | "tv" | "tw" | "tz" | "ua" | "ug" | "uk" | "us" | "uy" | "uz" | "va" | "vc" | "ve" | "vg" | "vi" | "vn" | "vu" | "wf" | "ws" | "xk" | "ye" | "yt" | "za" | "zm" | "zw";
        /**
         * RunTaskRequest
         * @description Create a new session, dispatch a task, or both.
         *
         *     - **No `sessionId` + no `task`**: creates an idle session (useful for uploading files before running a task).
         *     - **No `sessionId` + `task`**: creates a new session and immediately runs the task.
         *     - **`sessionId` + `task`**: dispatches the task to an existing idle session.
         *     - **`sessionId` + no `task`**: returns 422 — a task is required when targeting an existing session.
         */
        RunTaskRequest: {
            /**
             * Task
             * @description The natural-language instruction for the agent to execute (e.g. "Go to amazon.com and find the best-rated wireless mouse under $50"). Required when dispatching to an existing session.
             */
            task?: string | null;
            /**
             * @description The model to use. "gemini-3-flash" is fast and cheap, "claude-sonnet-4.6" is balanced, "claude-opus-4.6" is most capable. See BuModel for details.
             * @default claude-sonnet-4.6
             */
            model: components["schemas"]["BuModel"];
            /**
             * Sessionid
             * @description ID of an existing idle session to dispatch the task to. If omitted, a new session is created.
             */
            sessionId?: string | null;
            /**
             * Keepalive
             * @description If true, the session stays alive in idle state after the task completes instead of automatically stopping. This lets you dispatch follow-up tasks to the same session, preserving browser state and files.
             * @default false
             */
            keepAlive: boolean;
            /**
             * Maxcostusd
             * @description Maximum total cost in USD allowed for this session. The task will be stopped if this limit is reached. If omitted, a default limit applies (capped by your available balance).
             */
            maxCostUsd?: number | string | null;
            /**
             * Profileid
             * @description ID of a browser profile to load into the session. Profiles persist cookies, local storage, and other browser state across sessions. Create profiles via the Profiles API.
             */
            profileId?: string | null;
            /**
             * Workspaceid
             * @description ID of a workspace to attach to the session. Workspaces provide persistent file storage that carries across sessions. Create workspaces via the Workspaces API.
             */
            workspaceId?: string | null;
            /**
             * @description Country code for the browser proxy (e.g. "US", "DE", "JP"). Set to null to disable the proxy. The proxy routes browser traffic through the specified country, useful for accessing geo-restricted content.
             * @default us
             */
            proxyCountryCode: components["schemas"]["ProxyCountryCode"] | null;
            /**
             * Outputschema
             * @description A JSON Schema that the agent's final output must conform to. When set, the agent will return structured data matching this schema in the `output` field of the response. Example: {"type": "object", "properties": {"price": {"type": "number"}, "title": {"type": "string"}}}.
             */
            outputSchema?: {
                [key: string]: unknown;
            } | null;
            /**
             * Enablescheduledtasks
             * @description If true, the agent can create scheduled tasks that run on a recurring basis (e.g. "every Monday morning, check my inbox and summarize new emails"). Scheduled tasks are tied to your project and persist beyond the session. Note: all scheduled tasks are visible project-wide, so avoid enabling this in multi-user setups where task isolation is needed.
             * @default false
             */
            enableScheduledTasks: boolean;
            /**
             * Enablerecording
             * @description If true, records a video of the browser session. The recording URLs will be available in the `recordingUrls` field of the session response after the task completes.
             * @default false
             */
            enableRecording: boolean;
            /**
             * Skills
             * @description If true, enables built-in agent skills like Google Sheets integration and file management. Set to false to restrict the agent to browser-only actions.
             * @default true
             */
            skills: boolean;
            /**
             * Agentmail
             * @description If true, provisions a temporary email inbox (via AgentMail) for the session. The email address is available in the `agentmailEmail` field of the session response. Useful for tasks that require email verification or sign-ups.
             * @default true
             */
            agentmail: boolean;
            /**
             * Cachescript
             * @description Controls deterministic script caching. `null` (default): auto-detected — enabled when the task contains `@{{value}}` brackets and a workspace is attached. `true`: force-enable script caching even without brackets (caches the exact task). `false`: force-disable, even if brackets are present. When active, the first call runs the full agent and saves a reusable script. Subsequent calls with the same task template execute the cached script with $0 LLM cost. Requires workspace_id when enabled. Example: "Get prices from @{{https://example.com}} for @{{electronics}}".
             */
            cacheScript?: boolean | null;
        };
        /** SessionListResponse */
        SessionListResponse: {
            /**
             * Sessions
             * @description List of sessions.
             */
            sessions: components["schemas"]["SessionResponse"][];
            /**
             * Total
             * @description Total number of sessions matching the query.
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-indexed).
             */
            page: number;
            /**
             * Pagesize
             * @description Number of sessions per page.
             */
            pageSize: number;
        };
        /**
         * SessionNotFoundError
         * @description Error response when a session is not found
         */
        SessionNotFoundError: {
            /**
             * Detail
             * @default Session not found
             */
            detail: string;
        };
        /**
         * SessionResponse
         * @description Represents a session and its current state.
         *
         *     Poll this endpoint to track task progress. The `status` field indicates the session lifecycle stage,
         *     and `output` contains the agent's structured result once the task completes.
         */
        SessionResponse: {
            /**
             * Id
             * Format: uuid
             * @description Unique session identifier.
             */
            id: string;
            /** @description Current session lifecycle status. Progresses through: `created` (sandbox starting) → `idle` (ready, waiting for task) → `running` (task executing) → `stopped` / `timed_out` / `error`. Poll this field to track progress. */
            status: components["schemas"]["BuAgentSessionStatus"];
            /** @description The model tier used for this session. */
            model: components["schemas"]["BuModel"];
            /**
             * Title
             * @description Auto-generated short title summarizing the task. Available after the task starts running.
             */
            title?: string | null;
            /**
             * Output
             * @description The agent's final output. If `outputSchema` was provided, this will be structured data conforming to that schema. Otherwise it may be a free-form string or null. Populated once the task completes, regardless of whether `isTaskSuccessful` is true or false.
             */
            output?: unknown | null;
            /**
             * Outputschema
             * @description The JSON Schema that was requested for structured output, if any.
             */
            outputSchema?: {
                [key: string]: unknown;
            } | null;
            /**
             * Stepcount
             * @description Number of steps the agent has executed so far.
             * @default 0
             */
            stepCount: number;
            /**
             * Laststepsummary
             * @description Human-readable summary of the most recent agent step (e.g. "Clicking the Submit button"). Useful for showing real-time progress.
             */
            lastStepSummary?: string | null;
            /**
             * Istasksuccessful
             * @description Whether the task completed successfully. `true` if the agent achieved the goal, `false` if it failed or gave up, `null` if the task is still running or no task was dispatched.
             */
            isTaskSuccessful?: boolean | null;
            /**
             * Liveurl
             * @description URL to view the live browser session. Available immediately on session creation — can be embedded in an iframe to show the browser in real time.
             */
            liveUrl?: string | null;
            /**
             * Recordingurls
             * @description URLs to download session recordings. Only populated if `enableRecording` was set to true and the task has completed.
             * @default []
             */
            recordingUrls: string[];
            /**
             * Profileid
             * @description ID of the browser profile loaded in this session, if any.
             */
            profileId?: string | null;
            /**
             * Workspaceid
             * @description ID of the workspace attached to this session, if any.
             */
            workspaceId?: string | null;
            /** @description Country code of the proxy used for this session, or null if no proxy. */
            proxyCountryCode?: components["schemas"]["ProxyCountryCode"] | null;
            /**
             * Maxcostusd
             * @description Maximum cost limit in USD set for this session.
             */
            maxCostUsd?: string | null;
            /**
             * Totalinputtokens
             * @description Total LLM input tokens consumed by this session.
             * @default 0
             */
            totalInputTokens: number;
            /**
             * Totaloutputtokens
             * @description Total LLM output tokens consumed by this session.
             * @default 0
             */
            totalOutputTokens: number;
            /**
             * Proxyusedmb
             * @description Proxy bandwidth used in megabytes.
             * @default 0
             */
            proxyUsedMb: string;
            /**
             * Llmcostusd
             * @description Cost of LLM usage in USD.
             * @default 0
             */
            llmCostUsd: string;
            /**
             * Proxycostusd
             * @description Cost of proxy bandwidth in USD.
             * @default 0
             */
            proxyCostUsd: string;
            /**
             * Browsercostusd
             * @description Cost of browser compute time in USD.
             * @default 0
             */
            browserCostUsd: string;
            /**
             * Totalcostusd
             * @description Total session cost in USD (LLM + proxy + browser).
             * @default 0
             */
            totalCostUsd: string;
            /**
             * Screenshoturl
             * @description URL of the latest browser screenshot. This is a presigned URL that expires after 5 minutes. A new URL is generated each time you fetch the session.
             */
            screenshotUrl?: string | null;
            /**
             * Agentmailemail
             * @description Temporary email address provisioned for this session (via AgentMail). Only present if `agentmail` was enabled.
             */
            agentmailEmail?: string | null;
            /**
             * Createdat
             * Format: date-time
             * @description When the session was created.
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             * @description When the session was last updated.
             */
            updatedAt: string;
        };
        /**
         * SessionTimeoutLimitExceededError
         * @description Error response when session timeout exceeds the maximum allowed limit
         */
        SessionTimeoutLimitExceededError: {
            /**
             * Detail
             * @default Maximum session timeout is 4 hours (240 minutes).
             */
            detail: string;
        };
        /** StopSessionRequest */
        StopSessionRequest: {
            /**
             * @description How to stop the session. Use "task" to stop only the current task and keep the session alive, or "session" to destroy the sandbox entirely.
             * @default session
             */
            strategy: components["schemas"]["StopStrategy"];
        };
        /**
         * StopStrategy
         * @description Strategy for stopping a session.
         *
         *     - `task`: Stop the currently running task but keep the session alive in idle state. You can dispatch another task to the same session afterwards.
         *     - `session`: Stop the session entirely and destroy the sandbox. The session cannot be reused after this.
         * @enum {string}
         */
        StopStrategy: "task" | "session";
        /**
         * TooManyConcurrentActiveSessionsError
         * @description Error response when user has too many concurrent active sessions
         */
        TooManyConcurrentActiveSessionsError: {
            /**
             * Detail
             * @default Too many concurrent active sessions. Please wait for one to finish, kill one, or upgrade your plan.
             */
            detail: string;
        };
        /**
         * UpdateBrowserSessionRequest
         * @description Request model for updating browser session state.
         */
        UpdateBrowserSessionRequest: {
            /**
             * Action
             * @description The action to perform on the session
             */
            action: components["schemas"]["BrowserSessionUpdateAction"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkspaceCreateRequest
         * @description Request model for creating a new workspace.
         */
        WorkspaceCreateRequest: {
            /**
             * Name
             * @description Optional name for the workspace
             */
            name?: string | null;
        };
        /**
         * WorkspaceListResponse
         * @description Response model for paginated workspace list requests.
         */
        WorkspaceListResponse: {
            /**
             * Items
             * @description List of workspace views for the current page
             */
            items: components["schemas"]["WorkspaceView"][];
            /**
             * Total Items
             * @description Total number of items in the list
             */
            totalItems: number;
            /**
             * Page Number
             * @description Page number
             */
            pageNumber: number;
            /**
             * Page Size
             * @description Number of items per page
             */
            pageSize: number;
        };
        /**
         * WorkspaceUpdateRequest
         * @description Request model for updating a workspace.
         */
        WorkspaceUpdateRequest: {
            /**
             * Name
             * @description Optional name for the workspace
             */
            name?: string | null;
        };
        /**
         * WorkspaceView
         * @description View model for a workspace — persistent shared storage across sessions.
         */
        WorkspaceView: {
            /**
             * ID
             * Format: uuid
             * @description Unique identifier for the workspace
             */
            id: string;
            /**
             * Name
             * @description Optional name for the workspace
             */
            name?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Timestamp when the workspace was created
             */
            createdAt: string;
            /**
             * Updated At
             * Format: date-time
             * @description Timestamp when the workspace was last updated
             */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed). */
                page?: number;
                /** @description Number of sessions per page (max 100). */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_session_sessions__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StopSessionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_messages_sessions__session_id__messages_get: {
        parameters: {
            query?: {
                /** @description Cursor: return messages after this message ID */
                after?: string | null;
                /** @description Cursor: return messages before this message ID */
                before?: string | null;
                /** @description Maximum number of messages to return (max 100). */
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_browser_sessions_browsers_get: {
        parameters: {
            query?: {
                pageSize?: number;
                pageNumber?: number;
                filterBy?: components["schemas"]["BrowserSessionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserSessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_browser_session_browsers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrowserSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserSessionItemView"];
                };
            };
            /** @description Session timeout limit exceeded (maximum 4 hours) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionTimeoutLimitExceededError"];
                };
            };
            /** @description Profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileNotFoundError"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description Too many concurrent active sessions */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TooManyConcurrentActiveSessionsError"];
                };
            };
        };
    };
    get_browser_session_browsers__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserSessionView"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionNotFoundError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_browser_session_browsers__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBrowserSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserSessionView"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionNotFoundError"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    list_profiles_profiles_get: {
        parameters: {
            query?: {
                pageSize?: number;
                pageNumber?: number;
                query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProfileCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Subscription required for additional profiles */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsufficientCreditsError"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_profile_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileNotFoundError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_browser_profile_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_profiles__profile_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileNotFoundError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_workspaces_get: {
        parameters: {
            query?: {
                pageSize?: number;
                pageNumber?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workspace_workspaces__workspace_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workspace_workspaces__workspace_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspace_files_workspaces__workspace_id__files_get: {
        parameters: {
            query?: {
                prefix?: string;
                limit?: number;
                cursor?: string | null;
                includeUrls?: boolean;
                shallow?: boolean;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workspace_file_workspaces__workspace_id__files_delete: {
        parameters: {
            query: {
                /** @description Relative file path to delete */
                path: string;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_size_workspaces__workspace_id__size_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_workspace_files_workspaces__workspace_id__files_upload_post: {
        parameters: {
            query?: {
                /** @description Directory prefix to upload into (e.g. "uploads/") */
                prefix?: string;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_billing_billing_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Project for a given API key not found! */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountNotFoundError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
